In [22]:
import pandas as pd

In [23]:
path_positiva_1 = 'Clase_positiva_1'
path_positiva_0 = 'Clase_positiva_0'

In [26]:
positiva_1 = pd.read_csv(path_positiva_1)
positiva_1.head()

,Algoritmo,Accuracy,Balanced Accuracy,Error Rate,F1-Score,MCC,Precision,Recall,Specificity
0,1NN,0.4444,0.2222,0.5556,0.6154,0.0,1.0,0.4444,0.0
1,3NN,0.6667,0.3333,0.3333,0.8000,0.0,1.0,0.6667,0.0
2,5NN,0.7778,0.3889,0.2222,0.8750,0.0,1.0,0.7778,0.0
3,Naive Bayes,0.8611,0.4306,0.1389,0.9254,0.0,1.0,0.8611,0.0
4,RF,0.8889,0.4444,0.1111,0.9412,0.0,1.0,0.8889,0.0

In [25]:
positiva_0 = pd.read_csv(path_positiva_0)
positiva_0.head()

,Algoritmo,Accuracy,Balanced Accuracy,Error Rate,F1-Score,MCC,Precision,Recall,Specificity
0,1NN,0.4444,0.2222,0.5556,0.0,0.0,0.0,0.0,0.4444
1,3NN,0.6667,0.3333,0.3333,0.0,0.0,0.0,0.0,0.6667
2,5NN,0.7778,0.3889,0.2222,0.0,0.0,0.0,0.0,0.7778
3,Naive Bayes,0.8611,0.4306,0.1389,0.0,0.0,0.0,0.0,0.8611
4,RF,0.8889,0.4444,0.1111,0.0,0.0,0.0,0.0,0.8889